# Generated by Django 5.0.1 on 2024-07-06 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petName', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('details', models.CharField(max_length=50)),
                ('price', models.FloatField()),
            ],
        ),
    ]
