# Generated by Django 5.0.1 on 2024-06-29 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_form', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='desc',
            new_name='description',
        ),
    ]
