# Generated by Django 5.0.1 on 2024-07-23 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceProvider', '0002_carwashinfo_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountVerify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Carwash_name', models.CharField(max_length=50)),
                ('owner_name', models.CharField(max_length=50)),
                ('phone1', models.CharField(max_length=15)),
                ('phone2', models.CharField(max_length=15)),
                ('services', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='CarWashInfo',
        ),
    ]
