# Generated by Django 5.0.1 on 2024-07-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceProvider', '0004_accountverify_spid'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountverify',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
