# Generated by Django 5.0.1 on 2024-07-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceProvider', '0007_remove_services_spid_services_accountid'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountverify',
            name='services',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Services',
        ),
    ]
