# Generated by Django 5.0.1 on 2024-07-27 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceProvider', '0008_accountverify_services_delete_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=50)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='accountverify',
            name='services',
        ),
    ]
