# Generated by Django 5.0.1 on 2024-07-27 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceProvider', '0010_service_spid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='spid',
        ),
        migrations.AddField(
            model_name='service',
            name='bid',
            field=models.ForeignKey(db_column='bid', default=1, on_delete=django.db.models.deletion.CASCADE, to='serviceProvider.accountverify'),
            preserve_default=False,
        ),
    ]
