# Generated by Django 5.0.1 on 2024-07-28 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceProvider', '0013_business_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='business_details',
            name='phone_number',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
