# Generated by Django 5.0.1 on 2024-07-30 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_alter_bookings_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='booking_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
