# Generated by Django 5.0.1 on 2024-07-30 09:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_alter_bookings_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='booking_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 7, 30, 15, 8, 24, 368231)),
        ),
    ]
